backend:
  name: github
  repo: KANEKI757/kaneki-Graph
  branch: gh-pages
  auth_type: implicit
  app_id: Ov23liHEBVBSsz6nTibg

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "مقالات"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "محتوا", name: "body", widget: "markdown" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
